### ISSUE TITLE
Proyecto activo?

### ISSUE THREAD

**Issue by DIOHz0r** [gitnacho/symfony-docs-es#1]
Una pregunta simple, este proyecto aun sigue activo o se dejo de actualizar? veo que hacen referencia a la version 2.0 - 2.1 y la oficial hace referencia a la 2.3 como base

**Comment by gitnacho** [comment]
Una respuesta simple, este proyecto se dejó de actualizar, pero gran parte de la información todavía es útil.

**Comment by Joakiru** [comment]
Hay alguna forma de retomar este proyecto y buscar colaboradores? es la traduccion mas completa que he visto, me ha servido de mucho y sería una lastima que se perdiera por desactualización. Se podria tomar la 2.3.x he ir avanzando tomando siempre  para traducir la documentacion Long Term Support Release.

**Comment by gitnacho** [comment]
Bueno, gracias por los elogios, pero existe una traducción actualizada en http://librosweb.es/symfony_2_4, por lo tanto me parece que  es mejor dedicar el esfuerzo a otro proyecto, ¿No creen?

**Comment by DIOHz0r** [comment]
Es posible, lo que pasa es que en la documentación oficial de symfony.com aparece este repo y la version del librosweb de javiereguiluz no esta puesta en github todavia hasta donde se.

**Comment by DIOHz0r** [comment]
La documentación oficial traducida a otros odiomas fue depreciada por el proyecto symfony, ahora todo es en ingles.
